#!/bin/bash
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "\$item = new VehicleMake();"
    echo "\$item->make = '$line';"
    echo "\$item->vehicle_type_id = 1;"
    echo "\$item->save();"
    echo ""
done < "$1"
